project_root: .
paths:
  data_raw: data/raw
  data_interim: data/interim
  data_processed: data/processed
  artifacts: artifacts
train:
  target: Label
  test_size: 0.2
  random_state: 42
  model_type: RandomForest
  rf_n_estimators: 300
  rf_max_depth: null
  # Optional: add drop_cols if you want to exclude any ID/time columns
  drop_cols: []
